export const SUMMARY_APP_KEY= "LRMEZ2KDTVDS"
export const ARTICAL_APP_KEY= "EBC3AZ5XCAYY"
export const LOAD_ARTICAL_DETAIL= "detail/LOAD_ARTICAL_DETAIL"
export const RESET_ARTICALDETAIL= "detail/RESET_ARTICALDETAIL"